version: '2.2'

services:
  cxta:
    image: dockerhub-master.cisco.com/cxta-docker/cxta:19.10
    container_name: cxta_devnet
    working_dir: /home/devnet/cxta
    environment:
    - SELENIUM_URL=http://selenium:4444/wd/hub
    volumes:
    - ${WORKDIR:-./}:/home/devnet/cxta
    # to mount vagrant keys 
    - ${HOME}/.vagrant.d:/home/devnet/.vagrant.d
    tty: true
    stdin_open: true
    # Priveleged true for local runs needing openconnect, vpn tun creation, etc
    privileged: true
    network_mode: host
  docs:
    image: dockerhub-master.cisco.com/cxta-docker/cxta:19.10
    container_name: cxta_docs
    depends_on:
      - cxta
    command:
    - cd /tmp/ ; mkdocs serve -a 0.0.0.0:8081
    network_mode: host
