extra_css: [./extra.css]
nav:
- {Overview: ./index.md}
repo_name: GitHub
repo_url: https://github.com/oboehmer/CLEUR20-CXTA
site_author: Ava Thorn, Oliver Boehmer
site_description: Utilizing Cisco CXTA service framework to validate network elements
site_name: DEVWKS-1407
theme: {font: false, name: material}
